#!/usr/bin/env bash
#displays the content of the file /etc/passwd
#script should only display: username, user id and homedirectory

while IFS=: read -r passwd
do
	echo "$passwd" | cut -d ':' -f1, 3, 6
done < "/etc/passwd"
